# extract for the main study doc 

def main_sand(num):
    SANDBOX_MAP = [
        "https://docs.google.com/document/d/1W_9beF1YYjwdVfskZTNAtvn43G1dMT5yFt32WEXVpsw/edit?usp=sharing",
        "https://docs.google.com/document/d/1g2go4x-BKDxcunaH5ZJXKtKlb_vsxt1MuKUqC7-TeWQ/edit?usp=sharing",
        "https://docs.google.com/document/d/1dUYP93Yku2E4kdf046wImXqkgES_3zuvIuinoHFkJ14/edit?usp=sharing",
        "https://docs.google.com/document/d/1a8X_d6U09N6YunTispTH4hmG669dYvDelzS84pHyTDI/edit?usp=sharing",
        "https://docs.google.com/document/d/1xg-IbNK-vvn8ChlNUnxYcdURMBDfGKDjahmN88oe6TY/edit?usp=sharing",
        "https://docs.google.com/document/d/1ovpnhBG3oqhRaifUJPrQ_bjHwk7xMfX4uGdAafJwBt8/edit?usp=sharing",
        "https://docs.google.com/document/d/1XZ05NZEv1kB8Y8CTdnH0Ymls7KBzeG6Qn7YPIS_Es9U/edit?usp=sharing",
        "https://docs.google.com/document/d/1Rhqnw6e00K7JxazrvBiwGGIvSMfDvyXDrNvk6IqqpU4/edit?usp=sharing",
        "https://docs.google.com/document/d/1plUVWUxl3DohLhgaSi2BKUPHRLJ9BQNebql8sbClD7Y/edit?usp=sharing",
        "https://docs.google.com/document/d/1sk1bRVT5fUS8zsAo_8mZHmy4wxFncwr1C1N5cvYj9So/edit?usp=sharing",
        "https://docs.google.com/document/d/1CiLr4Cu7ZHi2pR9zBJ2EB3BsN8SDmUeFUdBCdwLHZCM/edit?usp=sharing",
        "https://docs.google.com/document/d/1V3dYPy_JGzP95S-bW6FWY3WguK2cPWuS1hfgN3zkypI/edit?usp=sharing",
        "https://docs.google.com/document/d/1HjTh37b4tTxyL6uaIZnuaB6BpHLLk5TOmkaamiIZBw0/edit?usp=sharing",
        "https://docs.google.com/document/d/1dGJA5e8a9Rm3qKG-VjH1a0jp9n8VIZe0lcGcjZa7N6o/edit?usp=sharing",
        "https://docs.google.com/document/d/116XlD_I0VrDKpP6WWbStJZtyA8XFwvG2j7xY_e2tIMI/edit?usp=sharing",
        "https://docs.google.com/document/d/1hj07WrRq5YyMJhpsgy9nGIrq3U8QoIUMVj5UunmMWJU/edit?usp=sharing",
        "https://docs.google.com/document/d/1Z2QZIdF817N8zTzO6GCKUyEuSlKJXVAsK8geNlKOIr8/edit?usp=sharing",
        "https://docs.google.com/document/d/1AIsSHiW4ktJTllx2huFDbI4dnnjPTlXSQncMFn4D_6s/edit?usp=sharing",
        "https://docs.google.com/document/d/1w04ngoijo71RQ9P_ZZX52iqHZdyTkjTQ46cGTohsYrw/edit?usp=sharing",
        "https://docs.google.com/document/d/10SiCbTRIXc1SnCIPhqmJlUTCpKUk1lqnxiCaxeXLmvs/edit?usp=sharing",
        "https://docs.google.com/document/d/1I0KoD60hXE-YPWWnpUC14akjkbqOvoOKQdIXLivOJ9U/edit?usp=sharing",
        "https://docs.google.com/document/d/1BDeUblsKc9WC9A4kd01HDhVYyxLHFneK2cpsG5Rtp24/edit?usp=sharing",
        "https://docs.google.com/document/d/1TgcT6IjKF7q8FGdZoOP_T75K-xa8hynhQ_3V8immYKg/edit?usp=sharing",
        "https://docs.google.com/document/d/1m8KmV--OXytXlh7jhM9cvLxTcUvvjt7b-Ci2cr_S-wY/edit?usp=sharing",
        "https://docs.google.com/document/d/1sQHjLSI6v0_G5jctw2AT0TDUDSyOabkwbuMuB2Q-4tM/edit?usp=sharing",
        "https://docs.google.com/document/d/1HP68OCqEWX1eDbmHuIP_AWJ7J5p6jrlQOArMjmm5KaE/edit?usp=sharing",
        "https://docs.google.com/document/d/1Pj2d2CGVQnd5dtjkWSlpEkB7fyFiPm-P1JsoLHrK2r0/edit?usp=sharing",
        "https://docs.google.com/document/d/1U6FLmNVgq_eCkHVVpu13vz-AWHkc9cNC-Q1F8zpBugE/edit?usp=sharing",
        "https://docs.google.com/document/d/1gwWTGG13F25MmgTbVRHzMMm1dRtvW_Liv4kk-3yDRjg/edit?usp=sharing",
        "https://docs.google.com/document/d/1sN6cAYA4whLpwknCsID24sNFxInrScwL1CAEpvXxFHU/edit?usp=sharing",
        "https://docs.google.com/document/d/1Ma0OpzHjoId6jSH8ARCpRuWSJIKtOd4s2tZ6oKxHt1A/edit?usp=sharing",
        "https://docs.google.com/document/d/1t3vb7K4SHrTf7bGEuspWk7XiwWfcRL9masZBw7Zifws/edit?usp=sharing",
        "https://docs.google.com/document/d/1txTjUv50fwF9kV0VmThc8ho90vGIUDLF3G2MCXXiYLI/edit?usp=sharing",
        "https://docs.google.com/document/d/1kVAW9l3JsQYfCCbFN3yOha12mwqjCsU5Sr7BineOQAE/edit?usp=sharing",
        "https://docs.google.com/document/d/19rkr8J0MoHDyix7RB9t-zh0EbHKQjq0iC2c7vyPPTdo/edit?usp=sharing",
        "https://docs.google.com/document/d/1VCx0Uf_s9qS3tCr43tvTyCAP2fsoHuna05xWaaGY1jA/edit?usp=sharing",
        "https://docs.google.com/document/d/1AdMg5zTEnhHuRU6xjZhZMDJfvDvK6G5FPv2dVwO9Qjk/edit?usp=sharing",
        "https://docs.google.com/document/d/11GI_dgT5QOguAMtkzYdww9BioTbh9_4M-6dR_cIGLmA/edit?usp=sharing",
        "https://docs.google.com/document/d/1F2dPZiKCooRBNAKI9sMwsEaLYWCO-LCaK82WReEShsk/edit?usp=sharing",
        "https://docs.google.com/document/d/1i7S-7sDPlJ8CM5VUM71kxM3ZAua7J75X0zWi0BKocVI/edit?usp=sharing",
        "https://docs.google.com/document/d/1TL2EBR6eVWThEAaHLhMc5DRmLpjetrxJlU7XNEoqJH0/edit?usp=sharing",
        "https://docs.google.com/document/d/1uVMke3nwQ58kZVaVzaE3XcZeguu_QRTy0MNfhRYEwQc/edit?usp=sharing",
        "https://docs.google.com/document/d/1b_4DkTzJegwSDIcZvQ-ovvpmlMaia-9f8aNgJnY39m8/edit?usp=sharing",
        "https://docs.google.com/document/d/1BT0vDezT2BjA0yHOOQqmEWbZp-LWZBlfXW-Ii1LA4rM/edit?usp=sharing",
        "https://docs.google.com/document/d/1N7O3Og7HD6QehkH2aYqzobPmHDOclp_DTzJL4jJJ-NI/edit?usp=sharing",
        "https://docs.google.com/document/d/1pw25T3glTm9ZDD3gHgfnHTDzoG0dYR49gv9zAzMSFoE/edit?usp=sharing",
        "https://docs.google.com/document/d/1RDLVisLIWhRuOMcLhVGeHXtwANsKN1WCxXl9mJoKXOY/edit?usp=sharing",
        "https://docs.google.com/document/d/1Q2ZdACfFWL2amqn8OaZAkhS8Le3Ib7qJWl1ZWbU03DI/edit?usp=sharing",
        "https://docs.google.com/document/d/1ywjKz-nO73aIkKCacVcZF6G6i_7Fc5eiqAITQbtaeZE/edit?usp=sharing",
        "https://docs.google.com/document/d/1OF-qITIDdUIHyakvM277-MJfUlCIoIQPmS3aHVmgpgU/edit?usp=sharing",
        "https://docs.google.com/document/d/1Vv6BxSSt7SkAi2G4L3E6wEfjhZ8ZFzWhjlLtAaWp-nE/edit?usp=sharing",
        "https://docs.google.com/document/d/10CvVYh1-xyC5evuT0aSu5YVY007Y7NWSPdO6HnKRVNA/edit?usp=sharing",
        "https://docs.google.com/document/d/1HimxvaQjidOjIQvhvn-iFt08whRHsbdd1n9p9R1V7ZU/edit?usp=sharing",
        "https://docs.google.com/document/d/1P9FebiQ8ZkIsW-khltkm_H3JdQ1cvGMnJP2SAlLWXpY/edit?usp=sharing",
        "https://docs.google.com/document/d/1ESipzDl05L3TmQBdcmj4FaAdDwJprFmO7OVsMf9868o/edit?usp=sharing",
        "https://docs.google.com/document/d/1dFlI3L4gdcatVTIv1qEgFzsFaG2VEPrQzVfu1cya_xQ/edit?usp=sharing",
        "https://docs.google.com/document/d/1yFiO8BuzDr1ksSJ4Uzxiq9OqXOSOYS_p13v8liUVGXQ/edit?usp=sharing",
        "https://docs.google.com/document/d/1cfOyQn3GGlWJav1Ec1iwqHwIksfhYGqDWzHFegq8OQ8/edit?usp=sharing",
        "https://docs.google.com/document/d/1pK7dPkbkeMlS9eYPmG1AKnol7euL3-ZnlhUgL7yNHKw/edit?usp=sharing",
        "https://docs.google.com/document/d/1RqSDTskK6ZIz_hiskDNKjvlRjCbYRXJxu1Y_hZO_JNk/edit?usp=sharing",
        "https://docs.google.com/document/d/1c-Z_f2Uct5j0BlEqZ7aRhZtZX6JHJSrgP5mDvi8qN4w/edit?usp=sharing",
        "https://docs.google.com/document/d/1R6gXPywd2v3diXlhkt4w4LQAVhIaU0Ra2MZMUrWGS4I/edit?usp=sharing",
        "https://docs.google.com/document/d/1i3yKXUhcL03QdwhfPCTd4PyFfAWEIYhe25oJ4DnrBD4/edit?usp=sharing",
        "https://docs.google.com/document/d/1v4-fGA4thSDhy1PnLbbE4nnQ2Pr3q3XyzEdpQOsTmIc/edit?usp=sharing"
    ]
    return SANDBOX_MAP[num]


    